version: '2'
services:
  app:
    image: vsokoltsov/uprogress
    build: .
    command: bash -l -c './bin/rails server -p 3000 -b 0.0.0.0 -d'
    environment:
      RAILS_ENV: $RAILS_ENV

    links:
      - db

    ports:
      - "80:3000"

  db:
    image: postgres:9.4.5
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres
volumes:
  postgres:
